version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci/cd"

  - package-ecosystem: "terraform"
    directory: "/terraform/environments/prod"
    schedule:
      interval: "weekly"
    labels:
      - "terraform"
